app/Http/Controllers/Api/BranchController.php
app/Models/Branch.php
database/migrations/2025_02_03_154635_create_branches_table.php
database/seeders/BranchSeeder.php
routes/api.php

refer:#1
Tạo api quản lý chi nhánh: thêm, sửa, xóa, xem

feat:create api branch_Management refer: #1

---

app/Http/Controllers/Api/CinemaController.php
app/Models/Cinema.php
database/migrations/2025_02_04_093851_create_cinemas_table.php
database/seeders/CinemaSeeder.php
routes/api.php

refer: #3 
quản lý rạp chiếu phim: thêm, sửa, xóa, xem danh sách rạp chiếu

feat: creat api cinema_Management refer: #3

---

app/Http/Controllers/Api/FoodController.php
app/Models/Food.php
composer.lock
database/migrations/2025_02_05_145953_create_foods_table.php
database/seeders/FoodSeeder.php
routes/api.php

API quản lý Food: Thêm, sửa, xóa, xem

feat: create food_Management refer:#9

---

app/Http/Controllers/Api/RoomController.php
app/Models/Branch.php
app/Models/Cinema.php
app/Models/Room.php
app/Models/Seat.php
app/Models/TypeRoom.php
app/Models/TypeSeat.php
database/migrations/2025_02_03_100000_create_type_rooms_table.php
database/migrations/2025_02_04_112110_create_rooms_table.php
database/migrations/2025_02_07_100105_create_type_seats_table.php
database/migrations/2025_02_07_100206_create_seats_table.php
database/seeders/DatabaseSeeder.php
database/seeders/RoomSeeder.php
database/seeders/SeatSeeder.php
database/seeders/TypeRoomSeeder.php
database/seeders/TypeSeatSeeder.php
note.md
routes/api.php

refer: #5 
api quản lý phòng chiếu: thêm, sửa, xóa, xem phòng chiếu
Đã tạo: router api cho room controller
Model đã tạo: Room, Seat, TypeRoom, TypeSeat
Bảng đã tạo:  type_rooms, type_seats, seat, room
Seeder: RoomSeeder, SeatSeeder, TypeRoomSeeder,TypeSeatSeeder
Controller/Api: RoomController

feat: creat room_Management refer: #5

---

app/Http/Controllers/Api/TypeRoomController.php
note.md
routes/api.php

refer: #17
Api quản lý loại phòng: thêm, sửa, xóa, xem loại phòng

feat: create typeRoom_Management refer: #17

---

app/Http/Controllers/Api/PostApiController.php
app/Models/Post.php
database/migrations/2025_02_07_075519_creat_posts_table.php
package-lock.json
package.json
resources/views/layouts/app.blade.php
routes/api.php
routes/web.php

refer: #13 
Api quản lý bài viết: Thêm, sửa, xóa, ẩn bài viết
Model: Post
PostApiController
Migrate: Post

feat: create PostManagement refer: #13

---

app/Http/Controllers/Api/TypeSeatController.php
note.md
routes/api.php

refer: #22 
Api quản lý loại ghế: thêm, sửa, xóa, xem loại ghế
model: TypeSeat

feat: create feature typeSeat_Management refer: #22

---

app/Http/Controllers/Api/ComboFoodController.php
app/Models/Combo.php
app/Models/ComboFood.php
app/Models/Food.php
database/migrations/2025_02_05_100310_create_food_table.php
database/migrations/2025_02_09_113110_create_combo_food_table.php
database/seeders/ComboFoodSeeder.php
database/seeders/DatabaseSeeder.php
routes/api.php

refer:#25
Api Quản lý combofood: Hiển thị , create, update
model ComboFood:  liên kêt khóa ngoại combo , food

Feature/combo food management refer:#25

---

database/migrations/2014_10_12_000000_create_users_table.php

feature/update_user-management #39

---

app/Http/Controllers/Api/FoodController.php
composer.lock

refer:#9
Cập nhập api food: validated

feat: update food refer:#9

---

app/Http/Controllers/Api/RankController.php
app/Models/Rank.php
database/migrations/2025_02_17_135217_create_ranks_table.php
database/seeders/DatabaseSeeder.php
database/seeders/RankSeeder.php
routes/api.php

refer:#44
API quản lý Ranks: Create, update, show, index, delete
RankSeeder, 
Model: Rank,
Migrations

Feature/ranks management refer:#44

---

app/Events/UserRegistered.php
app/Http/Controllers/Api/AuthController.php
app/Jobs/ResendVerificationEmailJob.php
app/Jobs/SendPasswordResetEmail.php
app/Listeners/SendVerificationEmail.php
app/Models/User.php
app/Providers/EventServiceProvider.php
database/migrations/2025_02_18_064550_create_jobs_table.php
note.md
routes/api.php

Api đổi mật khẩu người dùng
Dùng queue để gửi mail xác nhận đến người dùng

feature/queue #47

---

app/Http/Controllers/Api/CinemaController.php
app/Http/Controllers/Api/MovieController.php
app/Http/Controllers/Api/MovieReviewController.php
app/Models/Movie.php
app/Models/MovieReview.php
database/factories/MovieReviewFactory.php
database/migrations/2025_02_19_085635_create_movie_reviews_table.php
database/seeders/MovieReviewSeeder.php
routes/api.php

refer: #52 
Api quản lý movieReview: thêm, sửa, xóa, xem và cập nhật show movie

Feature/movie review  refer:#52

---

app/Http/Controllers/Api/ComboController.php
database/migrations/2025_02_05_100310_create_food_table.php
database/migrations/2025_02_08_100210_create_combos_table.php
routes/api.php

refer:#34
update ComboController: thêm indexActive

feat: update ComboController refer:#34

---

app/Http/Controllers/Api/ComboController.php
app/Http/Controllers/Api/MovieClientHomeController.php

refer:#49
Update MoviesClientHome thêm số lượng suất chiếu

feat: update MoviesClientHome refer:#49

---

app/Http/Controllers/Api/PostApiController.php
database/migrations/2025_02_17_000000_create_users_table.php
routes/api.php

Hiển thị thông tin người thêm bài viết

---

app/Http/Controllers/Api/ShowtimeController.php
routes/api.php
routes/web.php

refer: #61
api function pageshowtime

Feature/page showtime refer: #61

---

app/Http/Controllers/Api/ShowtimeController.php

refer: #69
Thêm Api function showtimeMovie vào showtimeController

feat: add showtimeMovie refer: #69

---

app/Http/Controllers/Api/AuthController.php
app/Models/Membership.php
database/migrations/2025_02_23_220029_create_memberships_table.php

Thêm tài khoản membership cho người mới đăng kí

feature/membership #72

---

app/Http/Controllers/Api/UserController.php
app/Models/User.php
app/Models/UserVoucher.php
app/Models/Voucher.php
database/seeders/UserVoucherSeeder.php
database/seeders/VoucherSeeder.php
routes/api.php

lấy ra thông tin các voucher có thể sử dụng của từng user

faeture/user_voucher 

---

app/Events/ChangeSeat.php
app/Events/SeatStatusChange.php
app/Http/Controllers/Api/ChooseSeatController.php
app/Http/Controllers/Api/ShowtimeController.php
composer.json
composer.lock
config/broadcasting.php

fix realtime and api

---

app/Http/Controllers/Api/UserController.php
app/Http/Controllers/Api/VoucherApiController.php
app/Models/Membership.php
app/Models/PointHistory.php
app/Models/Rank.php
app/Models/User.php
app/Models/Voucher.php
database/migrations/2025_02_09_081334_create_vouchers_table.php
database/migrations/2025_02_27_120251_create_point_histories_table.php
database/seeders/PointHistorySeeder.php
database/seeders/VoucherSeeder.php
routes/api.php

Api:thông tin membership, mức rank, lịch sử điểm của user

feature/point_membership #81

---

app/Http/Controllers/Api/ChooseSeatController.php
app/Http/Controllers/Api/UserController.php
app/Jobs/BroadcastSeatStatusChange.php
app/Jobs/ReleaseSeatHoldJob.php
app/Models/Seat.php
config/broadcasting.php
routes/api.php

Client develop

---

app/Http/Controllers/Api/TicketController.php
app/Models/Ticket.php
routes/api.php

#90 booking-history

---

app/Http/Controllers/Api/PaymentController.php

fix paymentcontroller

---

app/Http/Controllers/Api/PaymentController.php
routes/api.php

refer:#106
Thanh toán online Momo

feat: create Payment_Momo refer:#106

---

app/Http/Controllers/Api/PaymentController.php
app/Jobs/SendTicketEmail.php
app/Mail/TicketBookedMail.php
app/Models/Seat.php
app/Models/Ticket.php
app/Models/Ticket_Seat.php
resources/views/emails/ticket_booked.blade.php

gửi mail khi thanh toán thành công

feat: creat sendMailTickit refer:#108

---

app/Http/Controllers/Api/PaymentController.php

Update gủi mail cho user đặt vé

feat: update Momo refer:#106

---

database/migrations/2025_02_19_124427_create_user_vouchers_table.php

fix kiểu dữ liệu user_voucher

---

app/Http/Controllers/Api/PaymentController.php
app/Jobs/CancelVoucherJob.php
app/Jobs/SendTicketEmail.php
app/Mail/TicketBookedMail.php
app/Models/Ticket.php
resources/views/emails/ticket_booked.blade.php

refer: #120 fix_payment lấy dữ liệu từ frontend

feat: fix_payment refer:#120

---

app/Http/Controllers/Api/ReportController.php
routes/api.php

thay đổi phương thức post sang get

sửa thống kê

---

app/Http/Controllers/Api/ReportController.php
routes/api.php

feat: create Revenue_Statistics refer:#129

---

app/Http/Controllers/Api/PaymentController.php

update momo: PaymentIpn : Delete cache

feat:update paymentIpn refer:#106

---

app/Http/Controllers/Api/ReportController.php

feat: update Statistics refer:#129

---

app/Http/Controllers/Api/OverviewController.php
app/Http/Controllers/Api/ReportController.php
routes/api.php

Dashboard Tổng Quan (Overview)
Thống kê Doanh Thu (Revenue Analytics)
Thống kê Lượt Đặt Vé (Ticket Sales Report)
Thống kê Khách Hàng (Customer Insights)
Thống kê Xu Hướng Đặt Vé (Booking Trends)

thống kê #143

---

app/Http/Controllers/Api/ReportController.php
app/Models/Ticket_Combo.php
routes/api.php

doanh thu combo #143

---

app/Http/Controllers/Api/ReportController.php
app/Http/Controllers/Api/RoleController.php
routes/api.php

api hiển thị permission khi gọi ra role

sửa phân quyền

---

app/Http/Controllers/Api/AuthController.php
app/Http/Controllers/Api/UserController.php
app/Jobs/SendPasswordResetEmail.php
app/Models/User.php
app/Notifications/ResetPasswordCustom.php
config/app.php
routes/api.php

sửa lại quản lí user 
